### ISSUE TITLE
Projects cleaned: 66, Bytes deleted: 65.4GiB

### ISSUE THREAD

**Issue by SamuelMarks** [tbillington/kondo#123]
:partying_face:

(nice work @tbillington ; thanks for this)

**Comment by tbillington** [comment]
Hah! That's one of the bigger runs I've seen :) happy to have helped.

What kind of projects did you have?

**Comment by SamuelMarks** [comment]
:smiley_cat: :wastebasket: 

Lots of Rust and C ones. I cleared out my `node_modules` with a `fd -HIFuuutd 'node_modules' -x rm -r` a few days ago…

(318 git repos says `fd -HIuuug '.git' | wc -l`)
