### ISSUE TITLE
Is it possible to install kondo with UI from WinGet?

### ISSUE THREAD

**Issue by jbienz** [tbillington/kondo#128]
Installing from WinGet appears to only include the CLI. I use WinGet (UniGet) for managing many applications and I'd love to have the UI as an option there.

**Comment by tbillington** [comment]
Hey! That's a great idea

It would certainly be possible. I have a windows machine but I don't use it that often, and I wasn't the one that added winget support. The PR that added it is here https://github.com/microsoft/winget-pkgs/pull/131333/files.

It shouldn't be "too hard" to add something similar for the GUI if it's just replicating what's in the CLI config files with some minor changes.

**Comment by jbienz** [comment]
Totally understand, thanks @tbillington.

Hey @licon4812, any thoughts about adding UI? I'm not too familiar with the yaml format. I'm assuming it's a bit more complicated to add a shortcut than to add the exe to the path.

**Comment by licon4812** [comment]
When I initially added the cli version I looked into adding the GUI version and found a problem.

The winget team tends to not allow unsigned packages be added to the package manager, so I didn't bother attempting it.

If you guys like I can attempt it just so we get it on record and officially confirmed

**Comment by licon4812** [comment]
I have tested this locally and have opened a PR into winget

https://github.com/microsoft/winget-pkgs/pull/167496

**Comment by jbienz** [comment]
WOW! That was _incredibly_ fast turnaround time. I can already install it from UniGet. Thank you so much @licon4812!
