### ISSUE TITLE
compare to similar projects

### ISSUE THREAD

**Issue by matu3ba** [tbillington/kondo#27]
could you at least link similar projects?

**Comment by tbillington** [comment]
I do, in the readme. Do you know of any more than the one I listed? I don't actually know that many projects in this space!

**Comment by tbillington** [comment]
Or do you mean some kind of comparison table?

**Comment by matu3ba** [comment]
Comparison table would always be great.  
As I checked crates.io I searched for the keywords `cleanup` `free` `clean` (for which your crate sadly is not tagged) and found:
1. https://github.com/whitfin/detox  
2. https://github.com/woubuc/sweep  

For example I liked about detox that it checks what was lately used.  
The optimum would be to also show the latest building time attached to the projects, but that would require some shell setup.

**Comment by tbillington** [comment]
Oh I knew there was something I was forgetting, crate keywords! This is the first crate I've published. I'll have a look at those projects and see what can be done about a comparison. I'd also like to do the last modified date, I have another issue open for that.

**Comment by tbillington** [comment]
I did end up adding last modified date in a recent PR, it should be in the next release.
