### ISSUE TITLE
kondo-ui hung and crashed on macOS (after working well for a while)

### ISSUE THREAD

**Issue by atroche** [tbillington/kondo#39]
Details here from Apple's crash reporter tool: https://gist.github.com/atroche/12272ee32ac71ff20fed9bcf2226ab46

It wasn't in response to anything I did in the UI btw -- it seemed to happen while I was in another window.

Thanks for making this :) You freed up a bunch of space on my machine.

**Comment by tbillington** [comment]
You're welcome, glad you're finding use in it!

That's funny :) I appreciate the error dump, I'll see what I can do but all rendering and UI work is done by the [druid](https://github.com/linebender/druid) library, so if it doesn't pop out at me I might look upstream.

To help me debug, did you install from crates.io, or from source?

**Comment by atroche** [comment]
crates.io

**Comment by tbillington** [comment]
I couldn't replicate your issue, after installing from crates.io, deleting a bunch, then leaving it open for a few hours...

You're also quite a few OS versions behind the machines I have access to, and I don't really know how or have the motivation to try downgrading for this.

I'm tempted to close this as wontfix. Seems like a rare occurrence that I don't have the time to investigate, and you were able to use the program to fulfil it's purpose before it gave up ;)

**Comment by atroche** [comment]
yeah, no worries!
