### ISSUE TITLE
Directories you can delete for Python projects

### ISSUE THREAD

**Issue by pawamoy** [tbillington/kondo#44]
Virtual environments are often named `.venv`. For example, this is the name used by Poetry when creating the venv inside the project folder. They are also often named `venv`, though maybe sometimes such a directory could contain things the user wants to keep (never met this, but who knows). I guess the leading dot of `.venv` makes it safer to assume this is a virtualenv and that it can be removed.

Links:

- https://docs.python-guide.org/dev/virtualenvs/#lower-level-virtualenv
- https://python-poetry.org/docs/configuration/#virtualenvsin-project
- https://discuss.python.org/t/trying-to-come-up-with-a-default-directory-name-for-virtual-environments/3750

Additionally, [PEP582](https://www.python.org/dev/peps/pep-0582/#id2), which is used by some projects managers like PDM, says Python packages can be installed in a `__pypackages__` directory.

**Comment by pawamoy** [comment]
No interest/activity, closing, feel free to reopen 🙂

**Comment by tbillington** [comment]
Hey @pawamoy , I appreciate you opening the issue, apologies I haven't been able to dedicate as much time to kondo as I'd like :-)

I'd definitely be open to this functionality if you'd like to have a go at it in a PR! I haven't used Python seriously for years so I'm not super confident doing this myself.

If you'd like to try and implement this I'd be happy to assist. The core of kondos functionality is only 300 lines of _relatively_ straightforward code in https://github.com/tbillington/kondo/blob/master/kondo-lib/src/lib.rs. I've avoided as much abstractions as possible so far.
