### ISSUE TITLE
is it possible to run kondo recursively?

### ISSUE THREAD

**Issue by lucascr91** [tbillington/kondo#51]
I would like to run kondo in all directories below a directory (say `dir`). Is there something like `kondo -r dir`?

**Comment by tbillington** [comment]
Kondo is recursive by default :) It uses https://github.com/BurntSushi/walkdir internally.

If you've found a case where it isn't it could be a bug, do you have more information?

**Comment by lucascr91** [comment]
> Kondo is recursive by default :)

Cool. I didn't realize that at first because running it just deleted one folder at the top level, so I assume it's not recursive. Thank you for the clarification!

**Comment by tbillington** [comment]
There is a limitation currently where children of a directory that is identified as a project won't be searched. https://github.com/tbillington/kondo/issues/29

https://github.com/tbillington/kondo/blob/963e12f752a5baaf0356390853df53e9ca9a0dd8/kondo-lib/src/lib.rs#L244-L245

The original reason for it was tools like npm nest projects within projects. So kondo would detect the top level project, then return another thousand results of all of it's dependencies inside `node_modules`. It's definitely possible to be smarter about this, I just haven't spent the time to handle the case properly :)
