### ISSUE TITLE
Option for non-interactive mode

### ISSUE THREAD

**Issue by danieljb** [tbillington/kondo#52]
Hi, this is a question more than an issue. Sorry if this is not the right place for this.

I was wondering if there is an option to run kondo in non-interactive and maybe quiet mode? Something like `kondo -a ~/code` to remove all artifacts in one command without manual input.

Thanks for all the work put into this helpful tool!

**Comment by tbillington** [comment]
Hey @danieljb I thought it was a pretty neat idea :)

I implemented it in this PR, does it look roughly like what you had in mind?

https://github.com/tbillington/kondo/pull/53

**Comment by danieljb** [comment]
Hey @tbillington, that is exactly what I’ve been looking for. Awesome!

Thanks for the super fast reply and implementation!
