### ISSUE TITLE
Binary .exe under Windows 11 does not start

### ISSUE THREAD

**Issue by roboserg** [tbillington/kondo#59]
Downloaded latest binary, double click on .exe -> nothing happens

**Comment by tbillington** [comment]
Hey @roboserg thank you for taking the time to report this.

Unfortunately I don't have access to a win11 machine to test.

Could you please attempt to start the program via the [cmp prompt](https://www.minitool.com/news/run-program-from-cmd.html). That way if the program does crash upon starting it should allow you to see the output.

It's also possible there's some windows security protection blocking you from running downloaded .exe files.

**Comment by tbillington** [comment]
It's possible you ran the command line application, in that case it would have opened the terminal and potentially quit immediately.

You'll need to make sure you're running `kondo-ui.exe`, the latest release is from 0.3 https://github.com/tbillington/kondo/releases/tag/v0.3
