### ISSUE TITLE
Only delete old project (skip active project)

### ISSUE THREAD

**Issue by azzamsa** [tbillington/kondo#64]
Hi.

When I use `kondo` in my directory project, it deletes all the build artifacts in all directories. Including the active one.
[woubuc/sweep: Reduce the disk usage of your projects by removing dependencies & builds](https://github.com/woubuc/sweep) on the other hand, only delete inactive directory: old projects that haven't been changed in more than a month.

> Sweep (swp) finds old projects that haven't been changed in more than a month.

I thought I was missing some options. But I don't find any clue with `kondo --help`.

**Comment by azzamsa** [comment]
> As for automatically cleaning projects older than a certain date, I honestly hadn't thought of that, but it's something I may consider adding. Thank you for letting me know about that!

Yes, I think it doesn't need to be configurable as args. `last modified file > one month ` is enough to say the project is inactive.
Or we could create a poll in discussion what will be the default (hardcoded): one month or one week.

**Comment by tbillington** [comment]
I've added a printout of the last date a file in the project was modified, which was the first step towards something like this

```
/Users/choc/code/sp-liveview Cargo project (2 days ago)
  └─ target (615.6MiB)
  delete above artifact directories? ([y]es, [n]o, [a]ll, [q]uit): n

/Users/choc/code/rust-au Cargo project (3 months ago)
  └─ target (2.2GiB)
  delete above artifact directories? ([y]es, [n]o, [a]ll, [q]uit): n

/Users/choc/code/rust-prod-api Cargo project (2 months ago)
  └─ target (1.7GiB)
  delete above artifact directories? ([y]es, [n]o, [a]ll, [q]uit): q
```

**Comment by tbillington** [comment]
What about some kind of minimal filter syntax for passing to kondo.

For example `kondo projects-dir -f 1m` which would only show projects modified more than 1 month ago. Then you could do things like `kondo -f 2d` or `kondo -f 1y` etc.

You could combine that with the `--all` or `-a` flag to automatically clean the matching projects.

**Comment by azzamsa** [comment]
> You could combine that with the `--all` or `-a` flag to automatically clean the matching projects.

I think it should be the default, to avoid breaking current workflow.

**Comment by azzamsa** [comment]
@tbillington I think we need a new release that includes https://github.com/tbillington/kondo/pull/66 :)
