### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by tbillington** [tbillington/kondo#67]
To include recent changes, prompted by https://github.com/tbillington/kondo/issues/64.

**Comment by azzamsa** [comment]
Anything I can help to cut a release?

**Comment by tbillington** [comment]
Hey, appreciate the bump @azzamsa , not really, just on me to carve out some time to do this :)

**Comment by tbillington** [comment]
Released with https://github.com/tbillington/kondo/releases/tag/v0.6.

**Comment by azzamsa** [comment]
creates.io version still v2.0

**Comment by tbillington** [comment]
@azzamsa fixed!

**Comment by azzamsa** [comment]
Maybe we should we something like this https://github.com/BurntSushi/ripgrep/blob/master/RELEASE-CHECKLIST.md, to avoid future misses.
