### ISSUE TITLE
Add .angular folder

### ISSUE THREAD

**Issue by arlllk** [tbillington/kondo#71]
Since Angular 13 the compiler adds a compilation cache folder called `.angular/cache` by default, it would be useful to add it to the folders to be cleaned

docs: https://angular.io/cli/cache

**Comment by tbillington** [comment]
Thanks for the suggestion @arlllk !

I welcome you to make this PR, it should be a single line change much like this one https://github.com/tbillington/kondo/pull/47 :) just need to extend `PROJECT_NODE_DIRS`.
