### ISSUE TITLE
How to ignore some directory?

### ISSUE THREAD

**Issue by azzamsa** [tbillington/kondo#89]
Hi.

I want to ignore some directories because I tend to run `kondo $HOME`. 

```
~ took 20s
❯ kondo $(\ls --ignore=opt/nodebin)
/var/home/azzamsa/opt/nodebin Node project (5 minutes ago)
  └─ node_modules (177.8MiB)
  delete above artifact directories? ([y]es, [n]o, [a]ll, [q]uit): ^C
  
❯ kondo $(exa --ignore-glob ~/opt/nodebin)
/var/home/azzamsa/opt/nodebin Node project (6 minutes ago)
  └─ node_modules (177.8MiB)
  delete above artifact directories? ([y]es, [n]o, [a]ll, [q]uit): n
Projects cleaned: 0, Bytes deleted: 0.0B
```

Nothing works.

Any suggestions?

Thanks! :heart:

**Comment by tbillington** [comment]
I haven't put much thought into ignoring directories.

Is opt/nodebin part of your gitignore? It would be possible to modify kondo so that it respects gitignore when searching.

**Comment by tbillington** [comment]
Kondo will search recursively down each directory you provide it, so if `opt` is shown even if `opt/nodebin` is excluded, it will be found through `opt`, hope that makes sense.

**Comment by azzamsa** [comment]
It means no mechanism to tell kondo what directory to ignore?

**Comment by tbillington** [comment]
Not yet, but it could be added. Do you usually exclude directories by their exact path, or by glob?

How many directories do you exclude on average when you run kondo?

**Comment by azzamsa** [comment]
> How many directories do you exclude on average when you run kondo?

one, it contains all language server installed through npm.

> Not yet, but it could be added. Do you usually exclude directories by their exact path, or by glob?

So far, it is path.

**Comment by tbillington** [comment]
It would be possible to add an ignore argument, would something like this work? Then you wouldn't need to manually list the directories via ls/exa.

```sh
kondo --ignore-dir opt/nodebin
```

Just curious, do you often do any other kind of filtering/preprocessing before passing the directory list to kondo?

**Comment by azzamsa** [comment]
> Just curious, do you often do any other kind of filtering/preprocessing before passing the directory list to Kondo?

I run Kondo once a week, and the only directory in `kondo $HOME` that I want to ignore is just one. So, previously, I just answer `n` to the interactive prompt.

**Comment by tbillington** [comment]
Do you also use the date filter?

**Comment by tbillington** [comment]
@azzamsa could you try this branch and see if it handles your use-case ? thank you :)

https://github.com/tbillington/kondo/pull/90

**Comment by Aziks0** [comment]
I had the same suggestion, and #90 works perfectly! @tbillington

**Comment by tbillington** [comment]
Okay, thanks @Aziks0 , I'll merge it. Let me know if you have any issue :)

**Comment by tbillington** [comment]
I'll close this issue for now.

**Comment by azzamsa** [comment]
` kondo . --ignored-dirs opt/nodebin/` works like a charm! :tada:

**Comment by tbillington** [comment]
Thanks for confirming @azzamsa :)
