### ISSUE TITLE
CLI option to print artifact dirs in plaintext

### ISSUE THREAD

**Issue by tbillington** [tbillington/kondo#9]
Reddit user bcgroom mentioned a flag to output just a plain text line separated list of artifact directories. That way it could be passed/manipulated by other programs.

**Comment by tbillington** [comment]
implemented with `-a` CLI flag

**Comment by katrinleinweber** [comment]
Hi @tbillington 👋 Thanks for this awesome tool :-)

Can we reopen this? I think the `-a`/`--all` flag doesn't quite cover the use case that bcgroom mentioned:

```
$ kondo --all ~/…
/Users/…/… Node project
  └─ node_modules (2.3MiB)
  deleted 2.3MiB

Projects cleaned: 1, Bytes deleted: 2.3MiB
```

True, it _does output_ the directory path, but only in combination with the type, and with actually removing the data. It seems more like a `--force` mode.

However, for "pass[ing to] other programs" something more like a `--dry-run` or `--list-paths` option would be nice. I imagine that this would be useful for example to populate a backup exclusion list.

**Comment by katrinleinweber** [comment]
> only list artifact directories, do you also list the project folder, 

The former would be more useful, IMHO, because the artifact directory is the one that is emptied. If a project folder has multiple, they can always be grouped to highlight that fact.

> … list the project type somewhere?

Why not, as long as a separator that wouldn't be a valid symbol in a path is used. Any kind of `--dry-run` or `--list-paths` option would be more important than the formatting details.

A usecase would be to build a list of `exclude` patterns, for example for [BorgBackup](https://borgbackup.readthedocs.io/en/stable/quickstart.html#automating-backups). I mostly use [tmignore](https://github.com/samuelmeuli/tmignore), however.

**Comment by hustcer** [comment]
Looking forward to add `--recursive` and `--dry-run` options

**Comment by tbillington** [comment]
@hustcer kondo is recursive by default. But yes dry run would be helpful. It's not 100% necessary because it won't do anything until you tell it what to do, so dry run is a little less necessary.

The alternate I had in mind was more of a "discovery" command that would list all the projects, types, and sizes without taking any action.

What would you use dry run for ?

**Comment by hustcer** [comment]
> kondo is recursive by default. 

I don't think so, or maybe a bug? Look at the image below:
![Screenshot 2024-04-01 at 19 53 03](https://github.com/tbillington/kondo/assets/1161607/633604d5-ef54-4542-8189-ae4beeb66bed)

> What would you use dry run for ?

If the recursive works as expected, I want't to scan all the sub directories and to see if there is any dir need to be cleaned: I don't want to stop and make a choice for each inquiry.

> The alternate I had in mind was more of a "discovery" command that would list all the projects, types, and sizes without taking any action.

Great, that should work for my case.

**Comment by tbillington** [comment]
@hustcer 

> Look at the image below:

I should have been more specific, kondo is fully recursive by default (uses [walkdir](https://github.com/BurntSushi/walkdir) under the hood), however it doesn't recurse inside a found project #29  #55  #117 . I am loosely working on a rework in the background to address it, perhaps see if the [description here](https://github.com/tbillington/kondo/issues/111) addresses your use case.

> If the recursive works as expected, I want't to scan all the sub directories and to see if there is any dir need to be cleaned: I don't want to stop and make a choice for each inquiry.

To make sure I understand fully, instead of wanting to make a choice at each project, you want to do a dry run that lists everything, then (if you're okay with the output) run `kondo` again without dry run or interactive mode ? 

_Aside: there is the `-a, --all` flag currently which will automatically accept cleaning every found directory._

**Comment by hustcer** [comment]
> To make sure I understand fully, instead of wanting to make a choice at each project, you want to do a dry run that lists everything, then (if you're okay with the output) run kondo again without dry run or interactive mode ?

Yes, exactly

> I am loosely working on a rework in the background to address it, perhaps see if the https://github.com/tbillington/kondo/issues/111 addresses your use case.

I have read #111 carefully, I think this feature fulfills my needs, I have just subscribed that issue.

Thanks for the detailed response 👍
