### ISSUE TITLE
`--ignored-dirs` argument ignores the project itself

### ISSUE THREAD

**Issue by orhun** [tbillington/kondo#93]
I'm not sure if this is the expected behavior but I came across this issue while I was working on #92

To reproduce:

```sh
$ cargo new repro
$ cargo build
# target directory is created
$ kondo
Projects cleaned: 0, Bytes deleted: 0.0B
# nothing is cleaned
```

I think this is due to:

https://github.com/tbillington/kondo/blob/51828a1e96b0d0bdfd04dee210d30d77888172a9/kondo/src/main.rs#L57-L61

might be regression in #90

**Comment by tbillington** [comment]
Oh yep, I see what's happening, nice catch.

**Comment by tbillington** [comment]
Should be fixed in https://github.com/tbillington/kondo/commit/a48eb0968fea7e5436843b6a04cbdf86b8f8e263. Please let me know if there was still any issues :)

**Comment by orhun** [comment]
Works fine now, thank you for the fix!
